import fs from 'node:fs';
import path from 'node:path';
import { describe, expect, it } from 'vitest';
import {
  DEFAULT_SCIENCE_SKILL_IDS,
  LEGACY_SCIENCE_DEFAULT_SKILL_IDS,
  SCIENCE_ARTIFACT_SKILL_NAME,
  SCIENCE_CORE_SKILL_NAME,
  SCIENCE_VENDOR_CATALOG_SKILL_NAME,
  normalizeScienceDefaultSkillIds,
} from '@/common/chat/science';
import {
  SCIENCE_MATERIALIZED_SKILL_IDS,
  SCIENCE_SKILL_PACK_COUNTS,
  SCIENCE_SKILL_PACK_MANIFEST_PATH,
} from '@/common/chat/scienceSkills.generated';

type ScienceSkillManifest = {
  schema: string;
  counts: {
    total: number;
    byPack: Record<string, number>;
    byPackAvailable?: Record<string, number>;
    quarantinedScripts: number;
    restrictedDefault: number;
    clinicalBoundary: number;
  };
  skills: Array<{
    id: string;
    materializedPath: string;
    sourceUrl: string;
    license: string;
    executionPolicy: string;
    risk: string;
    clinicalBoundary: string;
    packId: string;
  }>;
};

const repoRoot = process.cwd();
const manifest = JSON.parse(
  fs.readFileSync(path.join(repoRoot, SCIENCE_SKILL_PACK_MANIFEST_PATH), 'utf8')
) as ScienceSkillManifest;

describe('OpenScience materialized Science skill pack', () => {
  it('keeps the generated manifest and generated constants in sync', () => {
    expect(manifest.schema).toBe('openscience.skill-pack.v1');
    expect(manifest.counts.total).toBe(SCIENCE_MATERIALIZED_SKILL_IDS.length);
    expect(manifest.counts.total).toBe(SCIENCE_SKILL_PACK_COUNTS.total);
    expect(manifest.counts.byPack.deepscientist).toBe(SCIENCE_SKILL_PACK_COUNTS.deepscientist);
    expect(manifest.counts.byPack.kdense).toBe(SCIENCE_SKILL_PACK_COUNTS.kdense);
    expect(manifest.counts.byPack.autoEmpirical).toBe(SCIENCE_SKILL_PACK_COUNTS.autoEmpirical);
    expect(manifest.counts.byPackAvailable?.autoEmpirical).toBe(SCIENCE_SKILL_PACK_COUNTS.autoEmpiricalAvailable);
    expect(manifest.counts.quarantinedScripts).toBe(SCIENCE_SKILL_PACK_COUNTS.quarantinedScripts);
    expect(manifest.counts.restrictedDefault).toBe(SCIENCE_SKILL_PACK_COUNTS.restrictedDefault);
    expect(manifest.counts.clinicalBoundary).toBe(SCIENCE_SKILL_PACK_COUNTS.clinicalBoundary);
  });

  it('loads the materialized skills by default without relying on the migration catalog', () => {
    expect(DEFAULT_SCIENCE_SKILL_IDS[0]).toBe(SCIENCE_CORE_SKILL_NAME);
    expect(DEFAULT_SCIENCE_SKILL_IDS[1]).toBe(SCIENCE_ARTIFACT_SKILL_NAME);
    expect(DEFAULT_SCIENCE_SKILL_IDS).not.toContain(SCIENCE_VENDOR_CATALOG_SKILL_NAME);
    expect(DEFAULT_SCIENCE_SKILL_IDS).toContain('ds-science');
    expect(DEFAULT_SCIENCE_SKILL_IDS).toContain('ds-review');
    expect(DEFAULT_SCIENCE_SKILL_IDS).toContain('kdense-database-lookup');
    expect(DEFAULT_SCIENCE_SKILL_IDS).toContain('kdense-scanpy');
    expect(DEFAULT_SCIENCE_SKILL_IDS).toContain('kdense-rdkit');
    expect(DEFAULT_SCIENCE_SKILL_IDS).toContain('aer-auto-empirical-research-skills');
    expect(DEFAULT_SCIENCE_SKILL_IDS).toContain('aer-statspai-skill');
  });

  it('keeps the AERS router lightweight while preserving catalog references', () => {
    const routerPath = path.join(repoRoot, 'resources/skills/aer-auto-empirical-research-skills');
    expect(fs.existsSync(path.join(routerPath, 'SKILL.md'))).toBe(true);
    expect(fs.existsSync(path.join(routerPath, 'references', 'aers-skills.json'))).toBe(true);
    expect(fs.existsSync(path.join(routerPath, 'references', 'TAXONOMY.md'))).toBe(true);
    expect(fs.existsSync(path.join(routerPath, 'skills'))).toBe(false);

    const aersSkills = manifest.skills.filter((skill) => skill.packId === 'autoEmpirical');
    expect(aersSkills.length).toBe(SCIENCE_SKILL_PACK_COUNTS.autoEmpirical);
    expect(aersSkills.length).toBeGreaterThan(0);
    expect(aersSkills.every((skill) => skill.license === 'CC-BY-SA-4.0')).toBe(true);
  });

  it('materializes every manifest skill as a first-class SKILL.md with provenance fields', () => {
    const ids = new Set<string>();
    for (const skill of manifest.skills) {
      expect(ids.has(skill.id)).toBe(false);
      ids.add(skill.id);
      expect(skill.sourceUrl).toMatch(/^https:\/\//u);
      expect(skill.license.length).toBeGreaterThan(0);
      expect(skill.executionPolicy).toMatch(
        /^(active_default|available_default|restricted_default|quarantined_script)$/u
      );
      expect(skill.risk).toMatch(/^(low|network|write|credential|external_compute)$/u);
      expect(skill.clinicalBoundary).toMatch(/^(none|medical_evidence_required)$/u);

      const skillPath = path.join(repoRoot, skill.materializedPath, 'SKILL.md');
      expect(fs.existsSync(skillPath)).toBe(true);
      const body = fs.readFileSync(skillPath, 'utf8');
      expect(body).toContain('Generated by OpenScience science skill materializer');
      expect(body).toContain('OpenScience Adapter');
      expect(body).toContain('How to Read This SKILL.md');
      expect(body).toContain('OpenScience SOP');
    }
    expect(ids.size).toBe(manifest.counts.total);
  });

  it('upgrades legacy catalog-only defaults to the materialized pack', () => {
    const normalized = normalizeScienceDefaultSkillIds(LEGACY_SCIENCE_DEFAULT_SKILL_IDS);
    expect(normalized).toEqual([...DEFAULT_SCIENCE_SKILL_IDS]);
    expect(normalized).toContain('ds-science');
    expect(normalized).toContain('kdense-database-lookup');
    expect(normalized).toContain('aer-auto-empirical-research-skills');
  });
});
